### ISSUE TITLE
ASG Deployment Strategy: waits for exact desired count

### ISSUE THREAD

**Issue by ehaynes99** [manheim/cf_deployer#32]
This method sleeps until the instance count is exactly equal to the desired. If auto-scaling were to scale the group higher, this would continue to sleep. It should be changed to sleep while < desired.

Note: We probably haven't run into this yet because it happens during the intermediate stage when both stacks are up, which would generally appear to be low load to either group.

**Comment by kmanning** [comment]
I feel like we should address this issue by simply "locking" auto-scaling during the deployment interval.  It's possible for autoscaling to kick in during a deployment (either up or down), which can cause problems for warmup.  If we simply prevent autoscaling for the duration of the deployment (set min/max to the current active desired), then reenable after a successful deployment (set min/max to what it *should* be), we solve this problem and more.

**Comment by kmanning** [comment]
Released in [v1.6.0](https://github.com/manheim/cf_deployer/tree/v1.6.0).  Closing.
