### ISSUE TITLE
ASG Deployment Strategy: handle rollback automatically

### ISSUE THREAD

**Issue by kmanning** [manheim/cf_deployer#39]
Using the ASG-based blue/green deployment strategy, if the deployment fails (particularly during warm-up), both the blue and green ASGs can end up with instances, effectively leaving both stacks "active".  It requires manual intervention to get the application deployable (cf_deployer will raise an error if both ASGs are active), and in the interim, customer requests can be routed to the possibly incompletely/incorrectly deployed ASG.

Ensure that a failure during the ASG-based blue/green deployment automatically "rolls back" - ie: sets the min/max of the new ASG to 0.

**Comment by qwcode** [comment]
+1

**Comment by kmanning** [comment]
Released in [v1.6.0](https://github.com/manheim/cf_deployer/tree/v1.6.0).  Closing.
