### ISSUE TITLE
Update does not update stack tags

### ISSUE THREAD

**Issue by rranshous** [manheim/cf_deployer#54]
I ran across some unexpected behavior while trying to update a stack's tags. I updated my configuration, ran the deploy and received back the message `No updates are to be performed.`

I had expected cf_deployer to send the new tags to the stack and perform an update.

The [`update_stack` method on the `Stack` object](https://github.com/manheim/cf_deployer/blob/master/lib/cf_deployer/stack.rb#L121) does does not merge tags in to the call arguments.

The `create_stack` method on the `Stack` object [does merge in the tags](https://github.com/manheim/cf_deployer/blob/master/lib/cf_deployer/stack.rb#L140).

Looking at the SDK docs it appears that the API call supports updating tags.

Is there a reason the tool does not support updating tags?

**Comment by jantman** [comment]
I don't have the full context on this, but I can make a guess...

The original code for this project was written in 2014.

According to the [archive.org Wayback Machine snapshot of the CloudFormation UpdateStack docs from November 2014](https://web.archive.org/web/20141109144709/http://docs.aws.amazon.com:80/AWSCloudFormation/latest/APIReference/API_UpdateStack.html), UpdateStack didn't originally support updating tags.

The "Tags" argument on UpdateStack doesn't show up in archive.org snapshots of the docs until sometime between September 2015 and July 2016 (back then AWS didn't maintain _any_ versioning of docs/changelogs/etc.).

If I had to guess, the ability to update tags was added around the same time as [CloudFormation Change Sets were announced in March 2016](https://aws.amazon.com/blogs/aws/new-change-sets-for-aws-cloudformation/).

All of that being said, while the docs don't seem to have been updated accordingly, this gem has been considered deprecated for quite a few years, and usage is certainly tailing off. To my knowledge, most internal teams that were using cf_deployer are now using either Elastic Beanstalk (either with https://github.com/ThoughtWorksStudios/eb_deployer or a similar tool) or Terraform.

**Comment by jantman** [comment]
To confirm my suspicion, as I detailed in #55, the gemspec for this project lists an aws-sdk dependency of `1.44.0`, but support for CF stack tagging wasn't introduced until [2.2.20](https://github.com/aws/aws-sdk-ruby/releases/tag/v2.2.20).

**Comment by rranshous** [comment]
Great information. Thank you for taking such care in evaluating the issue!

**Comment by rranshous** [comment]
The team has decided that we are going to work around this problem by using the CLI to update our stack's tags. We no longer need the feature described in this issue.

Thank you very much!
