### ISSUE TITLE
Warming up new stack ignores min/desired/max of existing stack

### ISSUE THREAD

**Issue by robsweet** [manheim/cf_deployer#9]
If the min/desired/max of a Blue stack have been modified manually, when Green is deployed, it only warms the new stack to the settings in the JSON instead of to what's set on the Blue stack.  It should respect the Blue stack's settings and throw a warning.

**Comment by robsweet** [comment]
Why was this closed?  Does the new logic from #31 work around it?

**Comment by ehaynes99** [comment]
This was actually fixed long ago (diff in auto_scaling_group_swap in https://github.com/manheim/cf_deployer/commit/1d2f9f26c95af811e918325e0d6bd03b50dad2ff ).

#31 was a regression caused by it, which is now also fixed.
